

version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: movies_db
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: your_password_here
      DB_NAME: movies_db
    depends_on:
      - db

volumes:
  db_data:
